version: '3'

services:
  ai-hedge-fund:
    build:
      context: .
    env_file:
      - .env
    volumes:
      # Optional: Mount für Persistenz von Daten
      - ./data:/app/data
    tty: true
    stdin_open: true
